language: go

sudo: false

go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"

before_install:
  - go get -t ./...

script:
  - GOMAXPROCS=4 GORACE="halt_on_error=1" go test -race -v ./...
