// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/ghostsquad/genny

package models

import "github.com/valyala/fastjson"

func UnmarshalTransitionFromObject(o *fastjson.Object) (Transition, error) {
	if o == nil {
		return Transition{}, nil
	}

	return UnmarshalTransition(o.String())
}
