// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/ghostsquad/genny

package v2

import "github.com/valyala/fastjson"

func UnmarshalTransitionFromValue(v *fastjson.Value) (Transition, error) {
	if v == nil {
		return Transition{}, nil
	}

	return UnmarshalTransition(v.String())
}
